" There needs to be a .vimrc file in the home directory with
" the following content:
" source ~/.config/vim/vimrc

syntax on
set nocompatible

" Show line number
set number

" Highlight current cursor poition by line and column
set cursorline
" set cursorcolumn

" tab configuration
set tabstop=4
set expandtab

" scroll margin from border
set scrolloff=5

" search options
set ignorecase
set incsearch













